<?php

$host="localhost:3306";
$user="root";
$pass="KQJYOXRC1";
$bd="casita_del_bazar";
$conn=mysqli_connect($host,$user,$pass,$bd);

if(!$conn){
die("Could no connect: ".mysqli_error());
}

$sql="SELECT PEDIDO.ID_PEDIDO,PEDIDO.FECHA_PEDIDO,METODO_PAGO.DESCRIPCION_METODO,METODO_ENVIO.METODO,ESTADO_PEDIDO.DESCRIPCION_ESTADO,USUARIO.NOMBRE,USUARIO.APELLIDO,PEDIDO.TOTAL,PEDIDO.DIRECCION,DEPARTAMENTO.DEPARTAMENTO_NOMBRE,PROVINCIA.PROVINCIA_NOMBRE,DISTRITO.DISTRITO_NOMBRE, USUARIO.TELEFONO,USUARIO.EMAIL,METODO_ENVIO.COSTO FROM DEPARTAMENTO INNER JOIN PROVINCIA ON DEPARTAMENTO.ID_DEPARTAMENTO=PROVINCIA.ID_DEPARTAMENTO INNER JOIN DISTRITO ON PROVINCIA.ID_PROVINCIA=DISTRITO.ID_PROVINCIA INNER JOIN PEDIDO ON DISTRITO.ID_DISTRITO=PEDIDO.ID_DISTRITO INNER JOIN USUARIO ON PEDIDO.ID_USUARIO=USUARIO.ID_USUARIO INNER JOIN METODO_PAGO ON PEDIDO.ID_METODO_PAGO=METODO_PAGO.ID_METODO INNER JOIN METODO_ENVIO ON PEDIDO.ID_METODO_ENVIO=METODO_ENVIO.ID_METODO INNER JOIN ESTADO_PEDIDO ON PEDIDO.ID_ESTADO_PEDIDO=ESTADO_PEDIDO.ESTADO";
mysqli_set_charset($conn, "utf8");
$json_array=array();

$retval=mysqli_query($conn,$sql);

if(mysqli_num_rows($retval)>0){

while($row=mysqli_fetch_assoc($retval)){

    $json_array[]=$row;

}
}else{

}
echo json_encode($json_array,JSON_UNESCAPED_UNICODE);
mysqli_close($conn);

?>
